# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('file', models.CharField(default='', max_length=1024, verbose_name='\u9644\u4ef6')),
                ('title', models.CharField(default='', max_length=1024, verbose_name='\u9644\u4ef6\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u9644\u4ef6',
                'verbose_name_plural': '\u9644\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='ExpertTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('username', models.CharField(default='', max_length=1024, verbose_name='\u4e13\u5bb6\u540d\u79f0')),
                ('email', models.CharField(default='', max_length=1024, verbose_name='email')),
            ],
            options={
                'verbose_name': '\u4e13\u5bb6\u56e2',
                'verbose_name_plural': '\u4e13\u5bb6\u56e2',
            },
        ),
        migrations.CreateModel(
            name='InvestmentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('username', models.CharField(default='', max_length=1024, verbose_name='\u6295\u8d44\u4eba\u540d\u79f0')),
                ('email', models.CharField(default='', max_length=1024, verbose_name='email')),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u56e2',
                'verbose_name_plural': '\u6295\u8d44\u56e2',
            },
        ),
        migrations.CreateModel(
            name='InvestmentTeamShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order_no', models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u53f7')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='\u6807\u9898')),
                ('img', models.CharField(default='', max_length=1024, verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u56e2\u5c55\u793a',
                'verbose_name_plural': '\u6295\u8d44\u56e2\u5c55\u793a',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(default='', max_length=255, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('theme', models.CharField(default='', max_length=255, verbose_name='\u4e3b\u63a7\u4e3b\u4f53')),
                ('total_amount', models.FloatField(blank=True, default=0, verbose_name='\u9879\u76ee\u6295\u8d44\u603b\u989d')),
                ('share_amount', models.FloatField(blank=True, default=0, verbose_name='\u9879\u76ee\u6295\u8d44\u4efd\u989d')),
                ('cycle', models.FloatField(blank=True, default=0, verbose_name='\u6295\u8d44\u5468\u671f')),
                ('expect_return', models.FloatField(blank=True, default=0, verbose_name='\u9884\u8ba1\u56de\u62a5')),
                ('progress', models.CharField(default='', max_length=255, verbose_name='\u9879\u76ee\u8fdb\u5ea6')),
                ('note', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('top', models.IntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0, verbose_name='\u662f\u5426\u7f6e\u9876')),
                ('top_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u7f6e\u9876\u65f6\u95f4')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='\u8bc4\u8bba\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='\u9879\u76ee'),
        ),
    ]
