# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171223_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf'),
        ),
    ]
