# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_project_read_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='project',
        ),
        migrations.AddField(
            model_name='attachment',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Attachment', verbose_name='\u9644\u4ef6'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
