# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180104_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='mail_id',
            field=models.TextField(blank=True, default='', verbose_name='\u90ae\u4ef6id'),
        ),
    ]
