# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-15 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_attachment_mail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mail_id',
            field=models.TextField(blank=True, default='', verbose_name='\u90ae\u4ef6id'),
        ),
    ]
