# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_comment_mail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_info',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='', max_length=1024, verbose_name='email'),
        ),
    ]
