# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180124_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expect_return',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u9884\u8ba1\u56de\u62a5'),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u9879\u76ee\u6295\u8d44\u4efd\u989d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u9879\u76ee\u6295\u8d44\u603b\u989d'),
        ),
    ]
