# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180129_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cycle',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u6295\u8d44\u5468\u671f'),
        ),
    ]
